name: Deploy Docker

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  docker:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: darkspadez
          password: ${{ secrets.GH_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: true
          tags: ghcr.io/darkspadez/deemon:latest
          labels: ${{ steps.meta.outputs.labels }}
